name: Create a PR to Develop Branch from Main
on:
  push:
    branches:
      - main
jobs:
  mainDevelop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: develop
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          title: Align Dev with Main
          body: Merge main into develop
          branch: main-to-dev
          base: develop
